"""Re-export shim: anti_block 已迁移至 shared 库"""

from content_aggregator_shared.shared.anti_block import (
    AntiBlockManager,
    ProxyManager,
    RequestScheduler,
    BehaviorSimulator,
    RetryStrategyExecutor,
    CDPBrowserManager,
    create_cdp_context,
    Proxy,
    ProxyStatus,
    ProxyType,
    RequestConfig,
    BehaviorConfig,
    RetryStrategy,
    RetryDecision,
    InteractionType,
    create_default_manager,
    integrate_with_collector,
    DEFAULT_REQUEST_CONFIG,
    DEFAULT_CDP_CONFIG,
    DEFAULT_BEHAVIOR_CONFIG,
)

__all__ = [
    "AntiBlockManager",
    "ProxyManager",
    "RequestScheduler",
    "BehaviorSimulator",
    "RetryStrategyExecutor",
    "CDPBrowserManager",
    "create_cdp_context",
    "Proxy",
    "ProxyStatus",
    "ProxyType",
    "RequestConfig",
    "BehaviorConfig",
    "RetryStrategy",
    "RetryDecision",
    "InteractionType",
    "create_default_manager",
    "integrate_with_collector",
    "DEFAULT_REQUEST_CONFIG",
    "DEFAULT_CDP_CONFIG",
    "DEFAULT_BEHAVIOR_CONFIG",
]
